### PR TITLE
Adds support for overriding Sentrys transport layer

### PR DESCRIPTION
**Pull request by AlbertoElias**
Temporary fix for #18 

Any suggestions to improve the test and/or documentation?

### CODE REVIEW

**Comment by pornel** [comment]
syntax error? https://github.com/Financial-Times/o-errors/pull/30/files#diff-64280bc385debac6d002e709f9ac0cddR224

**Comment by AlbertoElias** [comment]
@pornel why is that a syntax error? I'm fixing linting issues

**Comment by pornel** [comment]
It's an argument destructuring pattern without any arguments. Looks weird.

**Comment by AlbertoElias** [comment]
@pornel oh yes, I got mixed up, I'll remove that, thanks!

**Comment by AlbertoElias** [comment]
@pornel I've fixed different issues, including incorrect jsdoc which was throwing linting warnings

**Pull request merged**
