### PR TITLE
Add origami-version GitHub Action

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-errors bundle size difference from 4.0.2 to bf07f97a4978b600a636df849108a31d1b1399fd
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-errors bundle size difference from 4.0.2 to 1703b8db1ed81a72dedbdfd80a40405497d24694
No significant bundle size differences found.

**Comment by JakeChampion** [comment]
This helps achieve the OKR outlined here https://github.com/Financial-Times/origami/issues/39

**Comment by JakeChampion** [comment]
This helps achieve the OKR outlined here https://github.com/Financial-Times/origami/issues/39

**Pull request merged**
